version: 2.1
parameters:
  machine_image:
    type: string
    default: "ubuntu-2204:2023.02.1"

jobs:
  build:
    resource_class: xlarge
    machine:
      image:
      docker_layer_caching: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - gomodcache-{{ checksum "go.sum" }}
      - run:
          name: Docker login
          command: echo ${GCP_SERVICE_KEY} | docker login -u _json_key --password-stdin https://us.gcr.io
      - run:
          name: Build binary
          command: docker compose up build-binary
          no_output_timeout: 25m
      - run:
          name: Build docker image
          command: docker compose build build-image
          no_output_timeout: 25m
      - run:
          name: Push docker image
          command: |
            docker tag project-build-image us.gcr.io/marble-light-dev/bigquery-emulator:latest
            docker push us.gcr.io/marble-light-dev/bigquery-emulator:latest
      - save_cache:
          key: gomodcache-{{ checksum "go.sum" }}
          paths:
            - ~/project/_gomodcache

workflows:
  build:
    jobs:
      - build:
          context:
            - Shared
          filters:
            branches:
              only:
                - main