name: Go
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest" ]
        go-version: [ "1.17" ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: go test -race -v ./ -count=1
      env:
        CC: clang
        CXX: clang++
